version: "3"
services:
  db:
    image: mysql:8.0.28
    container_name: dockerMySQL
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: training
      MYSQL_HOST: dockerMySQL
    networks:
      - go-academy
    ports:
      - 3306:3306

networks:
  go-academy:
    external: true
